# Generated by Django 5.0.6 on 2024-06-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_archivedscheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edueligibility',
            name='choice',
            field=models.CharField(choices=[('SSLC', 'SSLC'), ('HSC', 'HSC'), ('DIPLOMA', 'Diploma'), ('PROFESSIONAL', 'Professional'), ('ARTS', 'ARTS'), ('P.G', 'P.G'), ('PH.D', 'Ph.D')], max_length=20),
        ),
    ]
