# Generated by Django 5.0.6 on 2024-06-04 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_edueligibility_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchivedScheme',
        ),
    ]
