# Generated by Django 5.0.6 on 2024-06-05 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_archivedscheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='edu_eligibility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.edueligibility'),
        ),
    ]
