# Generated by Django 5.0.6 on 2024-06-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_scheme_edu_eligibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casteeligibility',
            name='choice',
            field=models.CharField(choices=[('ALL_CASTE', 'ALL_CASTE'), ('MBC', 'MBC'), ('BC', 'BC'), ('OC', 'OC'), ('SC', 'SC'), ('ST', 'ST')], max_length=20, unique=True),
        ),
    ]
