# Generated by Django 5.0.6 on 2024-06-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_casteeligibility_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
